apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twstock.fullname" . }}-secrets
  labels:
    {{- include "twstock.labels" . | nindent 4 }}
type: Opaque
stringData:
  TWSTOCK_FINMIND_API_TOKEN: {{ .Values.secrets.finmindApiToken | quote }}
  TWSTOCK_FRED_API_KEY: {{ .Values.secrets.fredApiKey | quote }}
